[workspace]
members = [
    # Common
    "common/arrow",
    "common/base",
    "common/building",
    "common/cache",
    "common/context",
    "common/clickhouse-srv",
    "common/dal",
    "common/datablocks",
    "common/datavalues",
    "common/exception",
    "common/flight-rpc",
    "common/functions",
    "common/infallible",
    "common/io",
    "common/management",
    "common/planners",
    "common/meta/api",
    "common/meta/local-store",
    "common/meta/raft-store",
    "common/meta/sled-store",
    "common/meta/flight",
    "common/meta/types",
    "common/streams",
    "common/tracing",

    # Query
    "query",
    "metasrv",

    # SQL Fuzz
    "query/fuzz",

    # CLI
    "cli"
]

[profile.release]
debug = 1
codegen-units = 1   # Reduce number of codegen units to increase optimizations.

[profile.release.package]
arrow2 = { codegen-units = 4 }
databend-query = { codegen-units = 4 }

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
backtrace = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }
