[package]
name = "common-management"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-base= {path = "../base" }
common-exception= {path = "../exception"}
common-meta-api= {path = "../meta/api" }
common-meta-types= {path = "../meta/types"}
common-tracing= {path = "../tracing"}

async-trait = "0.1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.2.0"


[dev-dependencies]
common-base = { path = "../base" }
common-meta-local-store = {path = "../meta/local-store" }

mockall = "0.10.2"
tempfile = "3.2.0"
