[package]
name = "databend-cli"
version = "0.1.0"
description = "All-in-one tool for setting up, managing with Databend"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "databend-cli"
path = "src/bin/databend-cli.rs"

[features]

[dependencies]
# Workspace dependencies
databend-query = {path = "../query"}
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.4"
metasrv= {path = "../metasrv" }
common-meta-raft-store= {path = "../common/meta/raft-store"}
colored = "2.0.0"
comfy-table = "4.1.1"
dirs = "4.0.0"
dyn-clone = "1.0.4"
flate2 = "1.0.22"
indicatif = "0.16.2"
run_script = "^0.9.0"
rustyline = "9.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.8"
sysinfo = "0.20.4"
tar = "0.4.37"
thiserror = "1.0.30"
ureq = { version = "2.2.0", features = ["json"] }
nix = "0.22.2"
log = "0.4"

structopt = "0.3"
structopt-toml = "0.5.0"
portpicker = "0.1.1"
reqwest = { version = "0.11", features = ["json", "native-tls", "blocking"] }
libc = "0.2"
lexical-util = "0.8.1"

[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.2.0"
assert_cmd = "2.0.2"
predicates = "2.0.3"

[build-dependencies]
common-building = {path = "../common/building"}