[package]
name = "common-meta-api"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-exception = {path = "../../exception" }
common-planners = {path = "../../planners"}
common-meta-types = {path= "../types" }


futures = "0.3"
async-trait = "0.1"
